/**
 * Domain enums — formerly generated by Prisma from `schema.prisma`.
 *
 * These are the single source of truth for enumerated values across the app.
 * Mongoose schemas validate against `Object.values(X)`; DTOs and services
 * import these directly (replacing `import { X } from '@prisma/client'`).
 */

export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  AGENT = 'AGENT',
  INFLUENCER = 'INFLUENCER',
  SERVICE_PROVIDER = 'SERVICE_PROVIDER',
  CUSTOMER = 'CUSTOMER',
}

export enum ServiceStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum CategoryType {
  STAY = 'STAY',
  THING_TO_DO = 'THING_TO_DO',
  TOUR = 'TOUR',
  TRAVEL = 'TRAVEL',
  TRANSPORTATION = 'TRANSPORTATION',
  NOSY_BE = 'NOSY_BE',
  CORPORATE = 'CORPORATE',
  CULTURE = 'CULTURE',
  EVENT = 'EVENT',
  WORKPLACE = 'WORKPLACE',
  CO_WORKING = 'CO_WORKING',
}

export enum DiscountType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum CommissionType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum DiscountBadge {
  LIMITED_OFFER = 'LIMITED_OFFER',
  LOW_ROOM = 'LOW_ROOM',
  MANY_VIEWING_NOW = 'MANY_VIEWING_NOW',
  SAVE_PERCENT = 'SAVE_PERCENT',
  SAVE_VALUE = 'SAVE_VALUE',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentMethod {
  MVOLA = 'MVOLA',
  AIRTEL_MONEY = 'AIRTEL_MONEY',
  ORANGE_MONEY = 'ORANGE_MONEY',
  CARD = 'CARD',
  GIFT_CARD = 'GIFT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
}

export enum OtpPurpose {
  EMAIL_VERIFY = 'EMAIL_VERIFY',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TWO_FACTOR = 'TWO_FACTOR',
  PHONE_VERIFY = 'PHONE_VERIFY',
}

export enum PromoCodeType {
  PERCENT = 'PERCENT',
  FIXED = 'FIXED',
}

export enum AdPlacement {
  HOME_BANNER_1 = 'HOME_BANNER_1',
  HOME_BANNER_2 = 'HOME_BANNER_2',
  CATEGORY_BANNER_1 = 'CATEGORY_BANNER_1',
  CATEGORY_BANNER_2 = 'CATEGORY_BANNER_2',
  DETAIL_BANNER = 'DETAIL_BANNER',
}

export enum ChatRoomType {
  SUPPORT = 'SUPPORT',
  PROVIDER_CUSTOMER = 'PROVIDER_CUSTOMER',
  BOT = 'BOT',
}
