import {
  AlertCircle,
  ArrowRight,
  BadgeDollarSign,
  BarChart3,
  Box,
  Calendar,
  Captions,
  ChartSpline,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  Clock,
  Eye,
  EyeOff,
  FileText,
  Home,
  LayoutDashboard,
  Loader,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Moon,
  Newspaper,
  ScrollText,
  Search,
  Send,
  Settings,
  Settings2,
  Sun,
  TrendingUp,
  User,
  Users,
  X,
} from "lucide-react";
import { BiSupport } from "react-icons/bi";
import { FaGithub } from "react-icons/fa";
import { FaClockRotateLeft } from "react-icons/fa6";
import { IoIosTrendingDown, IoIosTrendingUp } from "react-icons/io";
import { IoCalendarOutline, IoCameraReverseOutline } from "react-icons/io5";
import {
  MdOutlineFeedback,
  MdOutlineFileDownload,
  MdOutlineInfo,
} from "react-icons/md";
import { SiGoogleforms } from "react-icons/si";
import {
  TbLayoutSidebarLeftCollapseFilled,
  TbLayoutSidebarRightCollapseFilled,
} from "react-icons/tb";

export const Icons = {
  LayoutDashboard,
  Box,
  Settings2,
  Users,
  BarChart3,
  FileText,
  Settings,
  User,
  Menu,
  X,
  Sun,
  Moon,
  Monitor,
  LogOut,
  ChevronLeft,
  ChevronRight,
  Search,
  Mail,
  MapPin,
  Calendar,
  AlertCircle,
  CheckCircle,
  Clock,
  TrendingUp,
  Eye,
  EyeOff,
  Lock,
  ArrowRight,
  Home,
  Loader,
  ScrollText,
  BadgeDollarSign,
  Send,
  Newspaper,
  Captions,
  TbLayoutSidebarLeftCollapseFilled,
  TbLayoutSidebarRightCollapseFilled,
  FaGithub,
  IoIosTrendingUp,
  IoIosTrendingDown,
  FaClockRotateLeft,
  ChartSpline,
  BiSupport,
  SiGoogleforms,
  MdOutlineFeedback,
  MdOutlineInfo,
  MdOutlineFileDownload,
  IoCalendarOutline,
  IoCameraReverseOutline,
};
